name: Build Go linux_amd64 and Win64

on:
    workflow_dispatch:


jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main

    - name: Set up Go
      uses: actions/setup-go@main
      with:
        go-version: '1.18'


    - name: Build go-ip2region
      working-directory: .
      run: |
          GOOS=linux GOARCH=amd64 go build -trimpath -ldflags="-w -s" -v
          GOOS=windows GOARCH=amd64 go build -trimpath -ldflags="-w -s" -v
          tree .
        
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@main
      with:
        name: go-ip2region
        path: |
            go-ip2region
            go-ip2region.exe
